name: Test

on:
  - push
  - pull_request

jobs:
  test:
    name: PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.0','7.1','7.2','7.3','7.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer
      - name: Install dependency
        run: composer install
      - if: matrix.php-versions == '7.0'
        name: Install n-other/php-sha3 on PHP 7.0
        run: composer require n-other/php-sha3:dev-master
      - name: Run tests
        run: ./vendor/bin/phpunit
